# Generated by Django 2.1.4 on 2018-12-19 19:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner', verbose_name='banner image')),
                ('index', models.IntegerField(default=0, verbose_name='banner index')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add time')),
            ],
            options={
                'verbose_name': 'banner goods',
                'verbose_name_plural': 'banner goods',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(default='', max_length=50, verbose_name='serial number')),
                ('name', models.CharField(help_text='name', max_length=100, verbose_name='name')),
                ('brief', models.TextField(max_length=500, verbose_name='brief')),
                ('desc', models.TextField(max_length=2000, verbose_name='brief')),
                ('hit_nums', models.IntegerField(default=0, verbose_name='hit nums')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='fav nums')),
                ('stock_nums', models.IntegerField(default=0, verbose_name='stock nums')),
                ('sold_nums', models.IntegerField(default=0, verbose_name='sold nums')),
                ('market_price', models.FloatField(default=0, verbose_name='market price')),
                ('shop_price', models.FloatField(default=0, verbose_name='shop price')),
                ('freight_free', models.BooleanField(default=True, verbose_name='is need freight fee')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='goods/images/', verbose_name='cover')),
                ('is_new', models.IntegerField(default=False, verbose_name='is new')),
                ('is_hot', models.IntegerField(default=False, verbose_name='is hot')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add time')),
            ],
            options={
                'verbose_name': 'goods',
                'verbose_name_plural': 'goods',
            },
        ),
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='category name', max_length=30, verbose_name='category name')),
                ('code', models.CharField(default='', help_text='category code', max_length=30, verbose_name='category code')),
                ('desc', models.TextField(default='', help_text='category description', verbose_name='category description')),
                ('category_type', models.IntegerField(choices=[(1, 'first'), (2, 'second'), (3, 'third')], help_text='category type', verbose_name='category type')),
                ('is_tab', models.BooleanField(default=False, help_text='is tab', verbose_name='is tab')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add time')),
                ('parent_category', models.ForeignKey(blank=True, help_text='parent category', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat', to='goods.GoodsCategory', verbose_name='parent category')),
            ],
            options={
                'verbose_name': 'goods category',
                'verbose_name_plural': 'goods category',
            },
        ),
        migrations.CreateModel(
            name='GoodsCategoryBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='brand name', max_length=30, verbose_name='brand name')),
                ('desc', models.TextField(default='', help_text='brand description', max_length=200, verbose_name='brand description')),
                ('image', models.ImageField(max_length=200, upload_to='brand/images')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add time')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='goods.GoodsCategory', verbose_name='goods category')),
            ],
            options={
                'verbose_name': 'brands',
                'verbose_name_plural': 'brands',
            },
        ),
        migrations.CreateModel(
            name='GoodsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='detail image')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add time')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='goods.Goods', verbose_name='goods')),
            ],
            options={
                'verbose_name': 'goods image',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsCategory', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='banner',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='goods'),
        ),
    ]
