# Generated by Django 2.1.4 on 2018-12-26 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_indexad'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IndexAd',
            new_name='IndexGoodsAd',
        ),
    ]
