# Generated by Django 2.1.4 on 2019-08-31 13:18

import datetime
from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20181226_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotSearchWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(default='', max_length=20, verbose_name='热搜词')),
                ('index', models.IntegerField(default=0, verbose_name='排序')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '热搜排行',
                'verbose_name_plural': '热搜排行',
            },
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': '首页轮播', 'verbose_name_plural': '首页轮播'},
        ),
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name': '商品信息', 'verbose_name_plural': '商品信息'},
        ),
        migrations.AlterModelOptions(
            name='goodscategory',
            options={'verbose_name': '商品类别', 'verbose_name_plural': '商品类别'},
        ),
        migrations.AlterModelOptions(
            name='goodscategorybrand',
            options={'verbose_name': '宣传品牌', 'verbose_name_plural': '宣传品牌'},
        ),
        migrations.AlterModelOptions(
            name='goodsimage',
            options={'verbose_name': '商品轮播', 'verbose_name_plural': '商品轮播'},
        ),
        migrations.AlterField(
            model_name='banner',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='banner', verbose_name='轮播图'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='index',
            field=models.IntegerField(default=0, verbose_name='轮播顺序'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='brief',
            field=models.TextField(max_length=500, verbose_name='商品简介'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsCategory', verbose_name='商品类目'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='goods/images/', verbose_name='封面图'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='desc',
            field=froala_editor.fields.FroalaField(),
        ),
        migrations.AlterField(
            model_name='goods',
            name='fav_nums',
            field=models.IntegerField(default=0, verbose_name='收藏数'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='freight_free',
            field=models.BooleanField(default=True, verbose_name='是否免运费'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='hit_nums',
            field=models.IntegerField(default=0, verbose_name='点击数'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='is_hot',
            field=models.IntegerField(default=False, verbose_name='是否热销'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='is_new',
            field=models.IntegerField(default=False, verbose_name='是否新品'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='market_price',
            field=models.FloatField(default=0, verbose_name='市场价格'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='name',
            field=models.CharField(help_text='商品名', max_length=100, verbose_name='商品名'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='shop_price',
            field=models.FloatField(default=0, verbose_name='本店价格'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='sn',
            field=models.CharField(default='', max_length=50, verbose_name='商品唯一货号'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='sold_nums',
            field=models.IntegerField(default=0, verbose_name='销售量'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='stock_nums',
            field=models.IntegerField(default=0, verbose_name='库存数'),
        ),
        migrations.AlterField(
            model_name='goodscategory',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='goodscategory',
            name='category_type',
            field=models.IntegerField(choices=[(1, '一级类目'), (2, '二级类目'), (3, '三级类目')], help_text='类目级别', verbose_name='类目级别'),
        ),
        migrations.AlterField(
            model_name='goodscategory',
            name='code',
            field=models.CharField(default='', help_text='类别 code', max_length=30, verbose_name='类别 code'),
        ),
        migrations.AlterField(
            model_name='goodscategory',
            name='desc',
            field=models.TextField(default='', help_text='类别描述', verbose_name='类别描述'),
        ),
        migrations.AlterField(
            model_name='goodscategory',
            name='is_tab',
            field=models.BooleanField(default=False, help_text='是否导航', verbose_name='是否导航'),
        ),
        migrations.AlterField(
            model_name='goodscategory',
            name='name',
            field=models.CharField(default='', help_text='类别名', max_length=30, verbose_name='类别名'),
        ),
        migrations.AlterField(
            model_name='goodscategory',
            name='parent_category',
            field=models.ForeignKey(blank=True, help_text='父类别', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat', to='goods.GoodsCategory', verbose_name='父类别'),
        ),
        migrations.AlterField(
            model_name='goodscategorybrand',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='goodscategorybrand',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='goods.GoodsCategory', verbose_name='商品类目'),
        ),
        migrations.AlterField(
            model_name='goodscategorybrand',
            name='desc',
            field=models.TextField(default='', help_text='品牌描述', max_length=200, verbose_name='品牌描述'),
        ),
        migrations.AlterField(
            model_name='goodscategorybrand',
            name='name',
            field=models.CharField(default='', help_text='品牌名', max_length=30, verbose_name='品牌名'),
        ),
        migrations.AlterField(
            model_name='goodsimage',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='goodsimage',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='goods.Goods', verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='goodsimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='indexgoodsad',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsCategory', verbose_name='商品类目'),
        ),
        migrations.AlterField(
            model_name='indexgoodsad',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='商品'),
        ),
    ]
