# Generated by Django 2.1.4 on 2019-09-01 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_auto_20190901_0923'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GoodsCategory',
            new_name='Category',
        ),
    ]
