# Generated by Django 2.1.4 on 2019-09-01 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_auto_20190901_0927'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GoodsCategoryBrand',
            new_name='CategoryBrand',
        ),
    ]
