# Generated by Django 2.1.4 on 2019-09-01 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_auto_20190901_0929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_type',
            new_name='level',
        ),
    ]
