# Generated by Django 2.1.4 on 2019-09-01 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_auto_20190901_0931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='parent_category',
            new_name='pid',
        ),
    ]
