# Generated by Django 2.1.4 on 2019-09-01 10:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0011_auto_20190901_0937'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trade', '0004_auto_20190901_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_sn', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='订单唯一编号')),
                ('trade_no', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='支付宝交易号')),
                ('nonce_str', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='随机加密串')),
                ('pay_status', models.CharField(choices=[('WAIT_BUYER_PAY', '交易创建'), ('TRADE_SUCCESS', '支付成功'), ('TRADE_FINISHED', '交易完成'), ('TRADE_CLOSED', '交易关闭'), ('paying', '待支付')], default='paying', max_length=20, verbose_name='支付状态')),
                ('pay_type', models.CharField(choices=[('alipay', '支付宝'), ('wechat', '微信')], default='alipay', max_length=20, verbose_name='支付类型')),
                ('leave_msg', models.CharField(max_length=200, verbose_name='订单留言')),
                ('mount', models.FloatField(default=0.0, verbose_name='订单金额')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('address', models.CharField(default='', max_length=100, verbose_name='收货人地址')),
                ('signer_name', models.CharField(default='', max_length=20, verbose_name='签收人')),
                ('signer_mobile', models.CharField(max_length=11, verbose_name='签收者电话')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '订单信息',
                'verbose_name_plural': '订单信息',
            },
        ),
        migrations.RenameModel(
            old_name='ShoppingCart',
            new_name='Cart',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='user',
        ),
        migrations.AlterField(
            model_name='ordergoods',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='trade.Order', verbose_name='订单信息'),
        ),
        migrations.DeleteModel(
            name='OrderInfo',
        ),
    ]
