# Generated by Django 2.1.4 on 2019-09-02 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_auto_20190901_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='mount',
            new_name='order_amount',
        ),
    ]
